apiVersion: v1
kind: Secret
metadata:
  name: videogame-store-secret
  namespace: videogame-store
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: videogame_store
  DATABASE_URL: postgresql://postgres:postgres@postgres.videogame-store.svc.cluster.local:5432/videogame_store?schema=public
  DIRECT_URL: postgresql://postgres:postgres@postgres.videogame-store.svc.cluster.local:5432/videogame_store?schema=public
